name: zip
on:
  pull_request:
    types:
      - closed
jobs:
    detect-directory-changes:
        name: "Detect Directory Changes"
        runs-on: ubuntu-latest
        outputs:
          changed: ${{ steps.detect.outputs.changed }}
        steps:
          - name: Checkout
            uses: actions/checkout@v2

          - name: Detect Directory Changes
            id: detect
            uses: tchupp/actions-detect-directory-changes@v0.1.7
    zip:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        needs: detect-directory-changes
        strategy:
            matrix:
                project: ${{ fromJSON(needs.detect-directory-changes.outputs.changed) }}
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Build ${{ matrix.project }}
            working-directory: ./${{ matrix.project }}
            run: ./.github/zip.sh
          - name: Create Pull Request
            id: cpr
            uses: peter-evans/create-pull-request@v4.2.3
            with:
                branch: patch/update-zip-and-json
                commit-message: Update zip and json
                delete-branch: true
          - name: merge PR
            env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: gh pr merge ${{ steps.pr.outputs.pull-request-url }} --merge
